export const Labels={
    Home:"Home",
    Ziply:"Ziply",
    Billing:"Billing",
    Account:"Account",
    Support:"Support",
    More:"More",
    Home_Icon:"home",
    Notification_Icon:"bell-o",
    Billing_Icon:"payment",
    Account_Icon:"account-circle",
    Support_Icon:"customerservice",
    Chat_Icon:"chatbubble-outline",
    More_Icon:"more-horizontal" ,
    Router_Icon:"router",
    Rocket_Icon:"rocket",
    Dollar_Icon:"dollar",
    NewsPaper_Icon:"newspaper-outline",
    List_Icon:"list",
    Right_Icon:"right",
    Play_Icon:"play-circle-outline",
    Settings_Icon:"md-settings-outline",
    Profile_Icon:"person-outline",
    Calender_Icon:"calendar-outline",
    Certificate_Icon:"certificate",
    Wifi_Icon:"wifi",
    Close_Icon:"close",
    Password_Icon:"eye-off",
    Login_Icon:"login",
    ShowPassword_Icon:"eye",
    FingerPrint_Icon:"finger-print-sharp"

}